project:
  type: website
  output-dir: docs
  

website:
  title: "  **Réunion Annuelle des Directeurs Nationaux du PEV,<br/> Kinshasa 2024**"
  navbar:
    search: true
    background: secondary
    logo: logo/logo-en.svg 
    logo-href: index.qmd
    
    right:
      - href: index.qmd
        text: Accueil
      - text: Enregistrements
        href: registrations.qmd
      - text: Agenda
        href: schedule.qmd
      - text: Préparation du Voyage
        href: travel.qmd
      - text: Contacts 
        href: about.qmd

format:
  html:
    theme: Simplex
    mainfont: Lato
    fontsize: 12pt
    max-width: 2000px
    css: styles.css
    toc: true
    toc-title: "Sur cette page"



