---
title: "RÉUNION ANNUELLE DES DIRECTEURS NATIONAUX DU PROGRAMME ELARGI DE LA VACCINATION POUR L’AFRIQUE CENTRALE"
format: html
execute: 
  warning: false
  message: false
  echo: false

---
\




```{r}
#| include: false

library(htmltools)
library(htmlwidgets)
```

## Dates and Location

Dates: **10^th^ - 12^th^ September 2024**

Liew: **Kinshasa, République Démocratique du Congo**

## Message de bienvenue


Nous avons le plaisir d'accueillir la réunion du Programme élargi de vaccination (PEV) du 1^er^ au 7 septembre 2024 à Kinshasa, en République démocratique du Congo. Nous sommes ravis de revenir à un format en personne pour cet événement important, qui rassemble la communauté mondiale dédiée à la vaccination et à la santé publique.

La réunion du PEV est réputée pour réunir des experts de la vaccination et des professionnels de la santé publique de différents secteurs, dans un environnement qui encourage le dialogue, l'échange d'idées et la recherche scientifique de pointe. Le thème de la réunion de cette année est "Immunisation et complexité : défis et réponses", qui couvrira tout le spectre des méthodes et pratiques contemporaines en matière d'immunisation. Des orateurs de renom présenteront des conférences plénières, des ateliers et des sessions interactives. Le programme, établi sur la base des résumés soumis, comprendra des présentations orales et des affiches illustrant les aspects théoriques et pratiques de chaque sous-discipline de l'immunisation. Cette réunion promet d'être une occasion inégalée de partager les expériences et l'expertise, offrant des possibilités phénoménales d'apprentissage, de croissance et de réseautage dans le domaine.

C'est la première fois que la réunion du PEV se tient en République démocratique du Congo, et Kinshasa offre un cadre vibrant et dynamique pour notre réunion. Kinshasa est une ville au patrimoine culturel riche et diversifié, qui offre un cadre unique à notre réunion.

Nous vous encourageons à prendre quelques jours avant ou après la réunion pour explorer la beauté et la culture de Kinshasa et de ses environs. En outre, envisagez de visiter d'autres destinations remarquables en République démocratique du Congo et dans la région pour compléter votre voyage à Kinshasa.

Nous vous invitons à commencer à vous préparer dès maintenant à ce qui promet d'être un mélange spécial de science de pointe dans un cadre vraiment unique. Nous nous réjouissons de vous voir à Kinshasa en septembre 2024 !

Le Directeur


The Director
