---
title: "Travel"
format: html
---

## Informations sur le voyage 

### Conditions d'entrée sur le territoire

La République Démocratique du Congo (RDC) applique strictement les conditions d'entrée et de sortie et les autres lois sur l'immigration. En cas de non-respect de ces exigences, le voyageur peut se voir refuser l'entrée sur le territoire, être détenu, expulsé ou considéré comme interdit de séjour en Afrique du Sud à l'avenir.


Veuillez consulter le site Web des représentation diplomatiques de la RDC dans vos pays respectifs afin connaître les conditions d'entrée et de sortie les plus récentes.

**Deux pages de passeport vierges consécutives** : La RDC exige que les voyageurs aient deux pages vierges consécutives dans leur passeport à chaque arrivée enRDC. L'entrée sur le territoire Congolais vous sera refusée si vous n'avez pas deux pages vierges consécutives.

**Passeport valable six mois** : Les voyageurs ne seront pas autorisés à franchir les frontières Congolaises si leur passeport n'a pas une date d'expiration minimale d'au moins six mois après le dernier jour du voyage. 




### Vaccins Obligatoires 

Les voyageurs entrant en RDC en provenance de pays désignés par l'OMS comme présentant un risque de transmission du virus de la fièvre jaune (YFV) doivent présenter leur certificat international de vaccination en cours de validité approuvé par l'Organisation mondiale de la santé (OMS) (carte jaune).

### Securité

Faites preuve de bon sens et prenez des mesures de sécurité élémentaires. Gardez vos objets de valeur sous clé et ne portez pas de montres ou de bijoux coûteux, ne montrez pas d'appareils photo coûteux et ne vous promenez pas dans des zones désertes. Fermez toujours les portes et les fenêtres de votre voiture à clé. En cas de doute, demandez à un guide ou à votre hébergement de vous donner des consignes de sécurité.


### Communication 

### Hébergement

**Hotel XXXXX** \
Distance par rapport au lieu de réunion: \
Cout Minimum:  xxxx CFA  \
Reservations: [google.com](google.com) \